import os


def root_file_paths():
    """change root filepaths here to your own"""
    origin_path=os.path.join('D:\\', 'recordings')  # A directory containing only data folders generated by SpikeGLX.
    external_path=os.path.join('E:\\', 'neuropixel_data')  # A folder on an external hardrive or other accessbile storage location.
    phy_ready_path=os.path.join('C:\\', 'phy_ready')  # A temp folder that can hold sessions ready to be manually curated. Will take up a lot of space if multiple sessions are queued.
    phy_holding_path=os.path.join('E:\\', 'phy_holding')  # Depricated.
    pi_path=os.path.join('C:\\', 'Users', 'Elissa', 'GoogleDrive', 'Code', 'Python', 'behavior_code', 'data')  # Location of the associated raspberry pi files.
    processed_data=os.path.join('C:\\', 'processed_data')  # Final desination for processed data.
  
    file_paths = {
        'origin_path': origin_path,
        'external_path': external_path,
        'phy_ready_path': phy_ready_path,
        'phy_holding_path': phy_holding_path,
        'pi_path': pi_path,
        'processed_data': processed_data
    }
    return file_paths
