import os


def root_file_paths(request=None):
    """change root filepaths here to your own"""
    # A directory containing only data folders generated by SpikeGLX.
    origin_path = os.path.join('D:\\', 'recordings')

    # A folder on an external hardrive or other accessbile storage location.
    external_path = os.path.join('E:\\', 'neuropixel_data')

    # A folder for sessions ready to be manually curated. Will take up a lot of space if multiple sessions are queued.
    phy_ready_path = os.path.join('Y:\\', 'phy_ready')

    # Location of the associated raspberry pi files.
    pi_path = os.path.join('C:\\', 'Users', 'Elissa', 'GoogleDrive', 'Code', 'Python', 'behavior_code', 'data')

    # Final destination for processed data.
    processed_data = os.path.join('C:\\', 'processed_data')

    # A destination for behavior data.
    behavior_only = os.path.join('C:\\', 'github', 'analysis_pipeline', 'z_behavior')

    file_paths = {
        'origin_path': origin_path,
        'external_path': external_path,
        'phy_ready_path': phy_ready_path,
        'pi_path': pi_path,
        'processed_data': processed_data,
        'behavior_only': behavior_only
    }
    if request is None:
        return file_paths
    elif request not in file_paths.keys():
        print('file_path name is incorrect')
        raise Exception
    else:
        return file_paths['request']
